### ISSUE TITLE
Response Retrieve from git to bot double

### ISSUE THREAD

**Issue by mzcoder-hub** [albinvar/Github-Telegram-Bot#4]
hello albi i have a lil problem in the bot, its look like the bot retrieve a double response and post it on the telegram

```
⚙️ 1 new commit to myrepo:developing

e6fcde8 : commit message

Pushed by : mzcoder-hub
⚙️ 1 new commit to myrepo:developing

e6fcde8 : commit message

Pushed by : mzcoder-hub
```

the response is double it should be only like this

```
⚙️ 1 new commit to myrepo:developing

e6fcde8 : commit message

Pushed by : mzcoder-hub
```
can you help to check it out ?

**Comment by albinvar** [comment]
Hopefully the issue was fixed on 7c28dac0909d7817fe55ee9f0e62b5cb55ff9f88
